# 服务配置文件，可修改本配置文件，并将此文件和安装文件放置到同一目录，
# 安装结束后会复制此文件到对应目录中，达到安装时统一配置的目的。
# 服务端口配置Ports：
# webapiPort：用于配置http接口，默认为8989,调用示例为
# 	http://localhost:8989/api/ReadMsg
# webapi读卡参数请参考开发文档
# socketioPort：用于配置Socket.io接口，默认为5000
# Https：设置https端口
# LocalhostOnly：配置服务是否只在本机访问，默认只能本机访问，如果需要在其他的计算机上访问服务，需要设置为false
# enableQuit：配置是否可以关闭服务，可以使用stop.bat来退出程序
# 
# ！！配置文件更改后请退出程序，重启SynCard.exe生效！！
# 

[Ports]
webapiPort: 8989
socketioPort: 5000

[Https]
webapiPort: 9199

[Access]
LocalhostOnly: true
enableQuit: true
enableUI: true
